# Generated by Django 4.2.11 on 2024-06-07 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='bookings.hall'),
            preserve_default=False,
        ),
    ]
