# Generated by Django 4.2.11 on 2024-06-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_hall_seat_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
